# -*- coding: utf-8 -*-
"""Instance_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lc_dj2Qhnfed_ywzrdmWb1lm0w3L_1LJ
"""

def replace_names(row):
    facts = row['facts']
    names = row['first_party'].split(' ')
    names2 = row['second_party'].split(' ')
    for name in names:
        if name in facts:
            facts = facts.replace(name, "wizard")
    for name2 in names2:
        if name2 in facts:
            facts = facts.replace(name2, "sorcerer")
    row['facts'] = facts
    return row

def swap_words(sentence):
    # Define the words to swap
    word_a = 'sorcerer'
    word_b = 'wizard'

    # Replace the words in the sentence
    new_sentence = sentence.replace(word_a, 'tempword').replace(word_b, word_a).replace('tempword', word_b)

    return new_sentence